# Generated by Django 5.0.3 on 2026-03-18 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPITask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("grade", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "Management"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_kpis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        limit_choices_to={"role": "Staff"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
