# Generated by Django 5.0.3 on 2026-03-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kpitask",
            name="grade",
        ),
        migrations.AddField(
            model_name="kpitask",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Yes", "Yes"), ("No", "No")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
