# Generated by Django 5.0.3 on 2026-03-19 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0002_remove_kpitask_grade_kpitask_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KPIEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "score",
                    models.CharField(
                        choices=[
                            ("Great", "Great"),
                            ("Good", "Good"),
                            ("Normal", "Normal"),
                            ("Bad", "Bad"),
                            ("Very Bad", "Very Bad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "Management"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluator_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        limit_choices_to={"role": "Staff"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpi.kpiobjective",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="KPITask",
        ),
    ]
